import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistBold = Geist({
  variable: "--font-geist-bold",
  subsets: ["latin"],
  weight: "700",
});

const geistRegular = Geist({
  variable: "--font-geist-regular",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistBold.variable} ${geistRegular.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
